/*
Infoblox DNS API

OpenAPI specification for Infoblox NIOS WAPI DNS objects

API version: 2.13.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dns

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/Infoblox-CTO/infoblox-nios-go-client/internal"
)

type RecordDnameAPI interface {
	/*
		RecorddnameGet Retrieve record:dname objects

		Returns a list of record:dname objects matching the search criteria

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return RecordDnameAPIRecorddnameGetRequest
	*/
	RecorddnameGet(ctx context.Context) RecordDnameAPIRecorddnameGetRequest

	// RecorddnameGetExecute executes the request
	//  @return ListRecordDnameResponse
	RecorddnameGetExecute(r RecordDnameAPIRecorddnameGetRequest) (*ListRecordDnameResponse, *http.Response, error)
	/*
		RecorddnamePost Create a record:dname object

		Creates a new record:dname object

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return RecordDnameAPIRecorddnamePostRequest
	*/
	RecorddnamePost(ctx context.Context) RecordDnameAPIRecorddnamePostRequest

	// RecorddnamePostExecute executes the request
	//  @return CreateRecordDnameResponse
	RecorddnamePostExecute(r RecordDnameAPIRecorddnamePostRequest) (*CreateRecordDnameResponse, *http.Response, error)
	/*
		RecorddnameReferenceDelete Delete a record:dname object

		Deletes a specific record:dname object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the record:dname object
		@return RecordDnameAPIRecorddnameReferenceDeleteRequest
	*/
	RecorddnameReferenceDelete(ctx context.Context, reference string) RecordDnameAPIRecorddnameReferenceDeleteRequest

	// RecorddnameReferenceDeleteExecute executes the request
	RecorddnameReferenceDeleteExecute(r RecordDnameAPIRecorddnameReferenceDeleteRequest) (*http.Response, error)
	/*
		RecorddnameReferenceGet Get a specific record:dname object

		Returns a specific record:dname object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the record:dname object
		@return RecordDnameAPIRecorddnameReferenceGetRequest
	*/
	RecorddnameReferenceGet(ctx context.Context, reference string) RecordDnameAPIRecorddnameReferenceGetRequest

	// RecorddnameReferenceGetExecute executes the request
	//  @return GetRecordDnameResponse
	RecorddnameReferenceGetExecute(r RecordDnameAPIRecorddnameReferenceGetRequest) (*GetRecordDnameResponse, *http.Response, error)
	/*
		RecorddnameReferencePut Update a record:dname object

		Updates a specific record:dname object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the record:dname object
		@return RecordDnameAPIRecorddnameReferencePutRequest
	*/
	RecorddnameReferencePut(ctx context.Context, reference string) RecordDnameAPIRecorddnameReferencePutRequest

	// RecorddnameReferencePutExecute executes the request
	//  @return UpdateRecordDnameResponse
	RecorddnameReferencePutExecute(r RecordDnameAPIRecorddnameReferencePutRequest) (*UpdateRecordDnameResponse, *http.Response, error)
}

// RecordDnameAPIService RecordDnameAPI service
type RecordDnameAPIService internal.Service

type RecordDnameAPIRecorddnameGetRequest struct {
	ctx            context.Context
	ApiService     RecordDnameAPI
	returnFields   *string
	returnFields2  *string
	maxResults     *int32
	returnAsObject *int32
	paging         *int32
	pageId         *string
	filters        *map[string]interface{}
	extattrfilter  *map[string]interface{}
}

// Enter the field names followed by comma
func (r RecordDnameAPIRecorddnameGetRequest) ReturnFields(returnFields string) RecordDnameAPIRecorddnameGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordDnameAPIRecorddnameGetRequest) ReturnFields2(returnFields2 string) RecordDnameAPIRecorddnameGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Enter the number of results to be fetched
func (r RecordDnameAPIRecorddnameGetRequest) MaxResults(maxResults int32) RecordDnameAPIRecorddnameGetRequest {
	r.maxResults = &maxResults
	return r
}

// Select 1 if result is required as an object
func (r RecordDnameAPIRecorddnameGetRequest) ReturnAsObject(returnAsObject int32) RecordDnameAPIRecorddnameGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

// Control paging of results
func (r RecordDnameAPIRecorddnameGetRequest) Paging(paging int32) RecordDnameAPIRecorddnameGetRequest {
	r.paging = &paging
	return r
}

// Page id for retrieving next page of results
func (r RecordDnameAPIRecorddnameGetRequest) PageId(pageId string) RecordDnameAPIRecorddnameGetRequest {
	r.pageId = &pageId
	return r
}

func (r RecordDnameAPIRecorddnameGetRequest) Filters(filters map[string]interface{}) RecordDnameAPIRecorddnameGetRequest {
	r.filters = &filters
	return r
}

func (r RecordDnameAPIRecorddnameGetRequest) Extattrfilter(extattrfilter map[string]interface{}) RecordDnameAPIRecorddnameGetRequest {
	r.extattrfilter = &extattrfilter
	return r
}

func (r RecordDnameAPIRecorddnameGetRequest) Execute() (*ListRecordDnameResponse, *http.Response, error) {
	return r.ApiService.RecorddnameGetExecute(r)
}

/*
RecorddnameGet Retrieve record:dname objects

Returns a list of record:dname objects matching the search criteria

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return RecordDnameAPIRecorddnameGetRequest
*/
func (a *RecordDnameAPIService) RecorddnameGet(ctx context.Context) RecordDnameAPIRecorddnameGetRequest {
	return RecordDnameAPIRecorddnameGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ListRecordDnameResponse
func (a *RecordDnameAPIService) RecorddnameGetExecute(r RecordDnameAPIRecorddnameGetRequest) (*ListRecordDnameResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *ListRecordDnameResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordDnameAPIService.RecorddnameGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:dname"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.maxResults != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_max_results", r.maxResults, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	if r.paging != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_paging", r.paging, "form", "")
	}
	if r.pageId != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_page_id", r.pageId, "form", "")
	}
	if r.filters != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "filters", r.filters, "form", "")
	}
	if r.extattrfilter != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "extattrfilter", r.extattrfilter, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type RecordDnameAPIRecorddnamePostRequest struct {
	ctx            context.Context
	ApiService     RecordDnameAPI
	recordDname    *RecordDname
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Object data to create
func (r RecordDnameAPIRecorddnamePostRequest) RecordDname(recordDname RecordDname) RecordDnameAPIRecorddnamePostRequest {
	r.recordDname = &recordDname
	return r
}

// Enter the field names followed by comma
func (r RecordDnameAPIRecorddnamePostRequest) ReturnFields(returnFields string) RecordDnameAPIRecorddnamePostRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordDnameAPIRecorddnamePostRequest) ReturnFields2(returnFields2 string) RecordDnameAPIRecorddnamePostRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r RecordDnameAPIRecorddnamePostRequest) ReturnAsObject(returnAsObject int32) RecordDnameAPIRecorddnamePostRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r RecordDnameAPIRecorddnamePostRequest) Execute() (*CreateRecordDnameResponse, *http.Response, error) {
	return r.ApiService.RecorddnamePostExecute(r)
}

/*
RecorddnamePost Create a record:dname object

Creates a new record:dname object

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return RecordDnameAPIRecorddnamePostRequest
*/
func (a *RecordDnameAPIService) RecorddnamePost(ctx context.Context) RecordDnameAPIRecorddnamePostRequest {
	return RecordDnameAPIRecorddnamePostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CreateRecordDnameResponse
func (a *RecordDnameAPIService) RecorddnamePostExecute(r RecordDnameAPIRecorddnamePostRequest) (*CreateRecordDnameResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *CreateRecordDnameResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordDnameAPIService.RecorddnamePost")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:dname"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.recordDname == nil {
		return localVarReturnValue, nil, internal.ReportError("recordDname is required and must be specified")
	}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if len(a.Client.Cfg.DefaultExtAttrs) > 0 && r.recordDname != nil {
		if r.recordDname.Extattrs == nil {
			r.recordDname.Extattrs = &map[string]ExtAttrs{}
		}
		for k, v := range a.Client.Cfg.DefaultExtAttrs {
			if _, ok := (*r.recordDname.Extattrs)[k]; !ok {
				(*r.recordDname.Extattrs)[k] = ExtAttrs{
					Value: v.Value,
				}
			}
		}
	}
	// body params
	localVarPostBody = r.recordDname
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type RecordDnameAPIRecorddnameReferenceDeleteRequest struct {
	ctx        context.Context
	ApiService RecordDnameAPI
	reference  string
}

func (r RecordDnameAPIRecorddnameReferenceDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.RecorddnameReferenceDeleteExecute(r)
}

/*
RecorddnameReferenceDelete Delete a record:dname object

Deletes a specific record:dname object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the record:dname object
	@return RecordDnameAPIRecorddnameReferenceDeleteRequest
*/
func (a *RecordDnameAPIService) RecorddnameReferenceDelete(ctx context.Context, reference string) RecordDnameAPIRecorddnameReferenceDeleteRequest {
	return RecordDnameAPIRecorddnameReferenceDeleteRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
func (a *RecordDnameAPIService) RecorddnameReferenceDeleteExecute(r RecordDnameAPIRecorddnameReferenceDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []internal.FormFile
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordDnameAPIService.RecorddnameReferenceDelete")
	if err != nil {
		return nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:dname/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type RecordDnameAPIRecorddnameReferenceGetRequest struct {
	ctx            context.Context
	ApiService     RecordDnameAPI
	reference      string
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Enter the field names followed by comma
func (r RecordDnameAPIRecorddnameReferenceGetRequest) ReturnFields(returnFields string) RecordDnameAPIRecorddnameReferenceGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordDnameAPIRecorddnameReferenceGetRequest) ReturnFields2(returnFields2 string) RecordDnameAPIRecorddnameReferenceGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r RecordDnameAPIRecorddnameReferenceGetRequest) ReturnAsObject(returnAsObject int32) RecordDnameAPIRecorddnameReferenceGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r RecordDnameAPIRecorddnameReferenceGetRequest) Execute() (*GetRecordDnameResponse, *http.Response, error) {
	return r.ApiService.RecorddnameReferenceGetExecute(r)
}

/*
RecorddnameReferenceGet Get a specific record:dname object

Returns a specific record:dname object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the record:dname object
	@return RecordDnameAPIRecorddnameReferenceGetRequest
*/
func (a *RecordDnameAPIService) RecorddnameReferenceGet(ctx context.Context, reference string) RecordDnameAPIRecorddnameReferenceGetRequest {
	return RecordDnameAPIRecorddnameReferenceGetRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return GetRecordDnameResponse
func (a *RecordDnameAPIService) RecorddnameReferenceGetExecute(r RecordDnameAPIRecorddnameReferenceGetRequest) (*GetRecordDnameResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *GetRecordDnameResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordDnameAPIService.RecorddnameReferenceGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:dname/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type RecordDnameAPIRecorddnameReferencePutRequest struct {
	ctx            context.Context
	ApiService     RecordDnameAPI
	reference      string
	recordDname    *RecordDname
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Object data to update
func (r RecordDnameAPIRecorddnameReferencePutRequest) RecordDname(recordDname RecordDname) RecordDnameAPIRecorddnameReferencePutRequest {
	r.recordDname = &recordDname
	return r
}

// Enter the field names followed by comma
func (r RecordDnameAPIRecorddnameReferencePutRequest) ReturnFields(returnFields string) RecordDnameAPIRecorddnameReferencePutRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordDnameAPIRecorddnameReferencePutRequest) ReturnFields2(returnFields2 string) RecordDnameAPIRecorddnameReferencePutRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r RecordDnameAPIRecorddnameReferencePutRequest) ReturnAsObject(returnAsObject int32) RecordDnameAPIRecorddnameReferencePutRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r RecordDnameAPIRecorddnameReferencePutRequest) Execute() (*UpdateRecordDnameResponse, *http.Response, error) {
	return r.ApiService.RecorddnameReferencePutExecute(r)
}

/*
RecorddnameReferencePut Update a record:dname object

Updates a specific record:dname object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the record:dname object
	@return RecordDnameAPIRecorddnameReferencePutRequest
*/
func (a *RecordDnameAPIService) RecorddnameReferencePut(ctx context.Context, reference string) RecordDnameAPIRecorddnameReferencePutRequest {
	return RecordDnameAPIRecorddnameReferencePutRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return UpdateRecordDnameResponse
func (a *RecordDnameAPIService) RecorddnameReferencePutExecute(r RecordDnameAPIRecorddnameReferencePutRequest) (*UpdateRecordDnameResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *UpdateRecordDnameResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordDnameAPIService.RecorddnameReferencePut")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:dname/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.recordDname == nil {
		return localVarReturnValue, nil, internal.ReportError("recordDname is required and must be specified")
	}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if len(a.Client.Cfg.DefaultExtAttrs) > 0 && r.recordDname != nil {
		if r.recordDname.Extattrs == nil {
			r.recordDname.Extattrs = &map[string]ExtAttrs{}
		}
		for k, v := range a.Client.Cfg.DefaultExtAttrs {
			if _, ok := (*r.recordDname.Extattrs)[k]; !ok {
				(*r.recordDname.Extattrs)[k] = ExtAttrs{
					Value: v.Value,
				}
			}
		}
	}
	// body params
	localVarPostBody = r.recordDname
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
