/*
Infoblox DNS API

OpenAPI specification for Infoblox NIOS WAPI DNS objects

API version: 2.13.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dns

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/Infoblox-CTO/infoblox-nios-go-client/internal"
)

type RecordTxtAPI interface {
	/*
		RecordtxtGet Retrieve record:txt objects

		Returns a list of record:txt objects matching the search criteria

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return RecordTxtAPIRecordtxtGetRequest
	*/
	RecordtxtGet(ctx context.Context) RecordTxtAPIRecordtxtGetRequest

	// RecordtxtGetExecute executes the request
	//  @return ListRecordTxtResponse
	RecordtxtGetExecute(r RecordTxtAPIRecordtxtGetRequest) (*ListRecordTxtResponse, *http.Response, error)
	/*
		RecordtxtPost Create a record:txt object

		Creates a new record:txt object

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return RecordTxtAPIRecordtxtPostRequest
	*/
	RecordtxtPost(ctx context.Context) RecordTxtAPIRecordtxtPostRequest

	// RecordtxtPostExecute executes the request
	//  @return CreateRecordTxtResponse
	RecordtxtPostExecute(r RecordTxtAPIRecordtxtPostRequest) (*CreateRecordTxtResponse, *http.Response, error)
	/*
		RecordtxtReferenceDelete Delete a record:txt object

		Deletes a specific record:txt object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the record:txt object
		@return RecordTxtAPIRecordtxtReferenceDeleteRequest
	*/
	RecordtxtReferenceDelete(ctx context.Context, reference string) RecordTxtAPIRecordtxtReferenceDeleteRequest

	// RecordtxtReferenceDeleteExecute executes the request
	RecordtxtReferenceDeleteExecute(r RecordTxtAPIRecordtxtReferenceDeleteRequest) (*http.Response, error)
	/*
		RecordtxtReferenceGet Get a specific record:txt object

		Returns a specific record:txt object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the record:txt object
		@return RecordTxtAPIRecordtxtReferenceGetRequest
	*/
	RecordtxtReferenceGet(ctx context.Context, reference string) RecordTxtAPIRecordtxtReferenceGetRequest

	// RecordtxtReferenceGetExecute executes the request
	//  @return GetRecordTxtResponse
	RecordtxtReferenceGetExecute(r RecordTxtAPIRecordtxtReferenceGetRequest) (*GetRecordTxtResponse, *http.Response, error)
	/*
		RecordtxtReferencePut Update a record:txt object

		Updates a specific record:txt object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the record:txt object
		@return RecordTxtAPIRecordtxtReferencePutRequest
	*/
	RecordtxtReferencePut(ctx context.Context, reference string) RecordTxtAPIRecordtxtReferencePutRequest

	// RecordtxtReferencePutExecute executes the request
	//  @return UpdateRecordTxtResponse
	RecordtxtReferencePutExecute(r RecordTxtAPIRecordtxtReferencePutRequest) (*UpdateRecordTxtResponse, *http.Response, error)
}

// RecordTxtAPIService RecordTxtAPI service
type RecordTxtAPIService internal.Service

type RecordTxtAPIRecordtxtGetRequest struct {
	ctx            context.Context
	ApiService     RecordTxtAPI
	returnFields   *string
	returnFields2  *string
	maxResults     *int32
	returnAsObject *int32
	paging         *int32
	pageId         *string
	filters        *map[string]interface{}
	extattrfilter  *map[string]interface{}
}

// Enter the field names followed by comma
func (r RecordTxtAPIRecordtxtGetRequest) ReturnFields(returnFields string) RecordTxtAPIRecordtxtGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordTxtAPIRecordtxtGetRequest) ReturnFields2(returnFields2 string) RecordTxtAPIRecordtxtGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Enter the number of results to be fetched
func (r RecordTxtAPIRecordtxtGetRequest) MaxResults(maxResults int32) RecordTxtAPIRecordtxtGetRequest {
	r.maxResults = &maxResults
	return r
}

// Select 1 if result is required as an object
func (r RecordTxtAPIRecordtxtGetRequest) ReturnAsObject(returnAsObject int32) RecordTxtAPIRecordtxtGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

// Control paging of results
func (r RecordTxtAPIRecordtxtGetRequest) Paging(paging int32) RecordTxtAPIRecordtxtGetRequest {
	r.paging = &paging
	return r
}

// Page id for retrieving next page of results
func (r RecordTxtAPIRecordtxtGetRequest) PageId(pageId string) RecordTxtAPIRecordtxtGetRequest {
	r.pageId = &pageId
	return r
}

func (r RecordTxtAPIRecordtxtGetRequest) Filters(filters map[string]interface{}) RecordTxtAPIRecordtxtGetRequest {
	r.filters = &filters
	return r
}

func (r RecordTxtAPIRecordtxtGetRequest) Extattrfilter(extattrfilter map[string]interface{}) RecordTxtAPIRecordtxtGetRequest {
	r.extattrfilter = &extattrfilter
	return r
}

func (r RecordTxtAPIRecordtxtGetRequest) Execute() (*ListRecordTxtResponse, *http.Response, error) {
	return r.ApiService.RecordtxtGetExecute(r)
}

/*
RecordtxtGet Retrieve record:txt objects

Returns a list of record:txt objects matching the search criteria

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return RecordTxtAPIRecordtxtGetRequest
*/
func (a *RecordTxtAPIService) RecordtxtGet(ctx context.Context) RecordTxtAPIRecordtxtGetRequest {
	return RecordTxtAPIRecordtxtGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ListRecordTxtResponse
func (a *RecordTxtAPIService) RecordtxtGetExecute(r RecordTxtAPIRecordtxtGetRequest) (*ListRecordTxtResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *ListRecordTxtResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordTxtAPIService.RecordtxtGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:txt"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.maxResults != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_max_results", r.maxResults, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	if r.paging != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_paging", r.paging, "form", "")
	}
	if r.pageId != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_page_id", r.pageId, "form", "")
	}
	if r.filters != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "filters", r.filters, "form", "")
	}
	if r.extattrfilter != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "extattrfilter", r.extattrfilter, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type RecordTxtAPIRecordtxtPostRequest struct {
	ctx            context.Context
	ApiService     RecordTxtAPI
	recordTxt      *RecordTxt
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Object data to create
func (r RecordTxtAPIRecordtxtPostRequest) RecordTxt(recordTxt RecordTxt) RecordTxtAPIRecordtxtPostRequest {
	r.recordTxt = &recordTxt
	return r
}

// Enter the field names followed by comma
func (r RecordTxtAPIRecordtxtPostRequest) ReturnFields(returnFields string) RecordTxtAPIRecordtxtPostRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordTxtAPIRecordtxtPostRequest) ReturnFields2(returnFields2 string) RecordTxtAPIRecordtxtPostRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r RecordTxtAPIRecordtxtPostRequest) ReturnAsObject(returnAsObject int32) RecordTxtAPIRecordtxtPostRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r RecordTxtAPIRecordtxtPostRequest) Execute() (*CreateRecordTxtResponse, *http.Response, error) {
	return r.ApiService.RecordtxtPostExecute(r)
}

/*
RecordtxtPost Create a record:txt object

Creates a new record:txt object

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return RecordTxtAPIRecordtxtPostRequest
*/
func (a *RecordTxtAPIService) RecordtxtPost(ctx context.Context) RecordTxtAPIRecordtxtPostRequest {
	return RecordTxtAPIRecordtxtPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CreateRecordTxtResponse
func (a *RecordTxtAPIService) RecordtxtPostExecute(r RecordTxtAPIRecordtxtPostRequest) (*CreateRecordTxtResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *CreateRecordTxtResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordTxtAPIService.RecordtxtPost")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:txt"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.recordTxt == nil {
		return localVarReturnValue, nil, internal.ReportError("recordTxt is required and must be specified")
	}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if len(a.Client.Cfg.DefaultExtAttrs) > 0 && r.recordTxt != nil {
		if r.recordTxt.Extattrs == nil {
			r.recordTxt.Extattrs = &map[string]ExtAttrs{}
		}
		for k, v := range a.Client.Cfg.DefaultExtAttrs {
			if _, ok := (*r.recordTxt.Extattrs)[k]; !ok {
				(*r.recordTxt.Extattrs)[k] = ExtAttrs{
					Value: v.Value,
				}
			}
		}
	}
	// body params
	localVarPostBody = r.recordTxt
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type RecordTxtAPIRecordtxtReferenceDeleteRequest struct {
	ctx        context.Context
	ApiService RecordTxtAPI
	reference  string
}

func (r RecordTxtAPIRecordtxtReferenceDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.RecordtxtReferenceDeleteExecute(r)
}

/*
RecordtxtReferenceDelete Delete a record:txt object

Deletes a specific record:txt object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the record:txt object
	@return RecordTxtAPIRecordtxtReferenceDeleteRequest
*/
func (a *RecordTxtAPIService) RecordtxtReferenceDelete(ctx context.Context, reference string) RecordTxtAPIRecordtxtReferenceDeleteRequest {
	return RecordTxtAPIRecordtxtReferenceDeleteRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
func (a *RecordTxtAPIService) RecordtxtReferenceDeleteExecute(r RecordTxtAPIRecordtxtReferenceDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []internal.FormFile
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordTxtAPIService.RecordtxtReferenceDelete")
	if err != nil {
		return nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:txt/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type RecordTxtAPIRecordtxtReferenceGetRequest struct {
	ctx            context.Context
	ApiService     RecordTxtAPI
	reference      string
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Enter the field names followed by comma
func (r RecordTxtAPIRecordtxtReferenceGetRequest) ReturnFields(returnFields string) RecordTxtAPIRecordtxtReferenceGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordTxtAPIRecordtxtReferenceGetRequest) ReturnFields2(returnFields2 string) RecordTxtAPIRecordtxtReferenceGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r RecordTxtAPIRecordtxtReferenceGetRequest) ReturnAsObject(returnAsObject int32) RecordTxtAPIRecordtxtReferenceGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r RecordTxtAPIRecordtxtReferenceGetRequest) Execute() (*GetRecordTxtResponse, *http.Response, error) {
	return r.ApiService.RecordtxtReferenceGetExecute(r)
}

/*
RecordtxtReferenceGet Get a specific record:txt object

Returns a specific record:txt object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the record:txt object
	@return RecordTxtAPIRecordtxtReferenceGetRequest
*/
func (a *RecordTxtAPIService) RecordtxtReferenceGet(ctx context.Context, reference string) RecordTxtAPIRecordtxtReferenceGetRequest {
	return RecordTxtAPIRecordtxtReferenceGetRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return GetRecordTxtResponse
func (a *RecordTxtAPIService) RecordtxtReferenceGetExecute(r RecordTxtAPIRecordtxtReferenceGetRequest) (*GetRecordTxtResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *GetRecordTxtResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordTxtAPIService.RecordtxtReferenceGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:txt/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type RecordTxtAPIRecordtxtReferencePutRequest struct {
	ctx            context.Context
	ApiService     RecordTxtAPI
	reference      string
	recordTxt      *RecordTxt
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Object data to update
func (r RecordTxtAPIRecordtxtReferencePutRequest) RecordTxt(recordTxt RecordTxt) RecordTxtAPIRecordtxtReferencePutRequest {
	r.recordTxt = &recordTxt
	return r
}

// Enter the field names followed by comma
func (r RecordTxtAPIRecordtxtReferencePutRequest) ReturnFields(returnFields string) RecordTxtAPIRecordtxtReferencePutRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordTxtAPIRecordtxtReferencePutRequest) ReturnFields2(returnFields2 string) RecordTxtAPIRecordtxtReferencePutRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r RecordTxtAPIRecordtxtReferencePutRequest) ReturnAsObject(returnAsObject int32) RecordTxtAPIRecordtxtReferencePutRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r RecordTxtAPIRecordtxtReferencePutRequest) Execute() (*UpdateRecordTxtResponse, *http.Response, error) {
	return r.ApiService.RecordtxtReferencePutExecute(r)
}

/*
RecordtxtReferencePut Update a record:txt object

Updates a specific record:txt object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the record:txt object
	@return RecordTxtAPIRecordtxtReferencePutRequest
*/
func (a *RecordTxtAPIService) RecordtxtReferencePut(ctx context.Context, reference string) RecordTxtAPIRecordtxtReferencePutRequest {
	return RecordTxtAPIRecordtxtReferencePutRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return UpdateRecordTxtResponse
func (a *RecordTxtAPIService) RecordtxtReferencePutExecute(r RecordTxtAPIRecordtxtReferencePutRequest) (*UpdateRecordTxtResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *UpdateRecordTxtResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordTxtAPIService.RecordtxtReferencePut")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:txt/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.recordTxt == nil {
		return localVarReturnValue, nil, internal.ReportError("recordTxt is required and must be specified")
	}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if len(a.Client.Cfg.DefaultExtAttrs) > 0 && r.recordTxt != nil {
		if r.recordTxt.Extattrs == nil {
			r.recordTxt.Extattrs = &map[string]ExtAttrs{}
		}
		for k, v := range a.Client.Cfg.DefaultExtAttrs {
			if _, ok := (*r.recordTxt.Extattrs)[k]; !ok {
				(*r.recordTxt.Extattrs)[k] = ExtAttrs{
					Value: v.Value,
				}
			}
		}
	}
	// body params
	localVarPostBody = r.recordTxt
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
