/*
Infoblox DNS API

OpenAPI specification for Infoblox NIOS WAPI DNS objects

API version: 2.13.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dns

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/Infoblox-CTO/infoblox-nios-go-client/internal"
)

type RecordCaaAPI interface {
	/*
		RecordcaaGet Retrieve record:caa objects

		Returns a list of record:caa objects matching the search criteria

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return RecordCaaAPIRecordcaaGetRequest
	*/
	RecordcaaGet(ctx context.Context) RecordCaaAPIRecordcaaGetRequest

	// RecordcaaGetExecute executes the request
	//  @return ListRecordCaaResponse
	RecordcaaGetExecute(r RecordCaaAPIRecordcaaGetRequest) (*ListRecordCaaResponse, *http.Response, error)
	/*
		RecordcaaPost Create a record:caa object

		Creates a new record:caa object

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return RecordCaaAPIRecordcaaPostRequest
	*/
	RecordcaaPost(ctx context.Context) RecordCaaAPIRecordcaaPostRequest

	// RecordcaaPostExecute executes the request
	//  @return CreateRecordCaaResponse
	RecordcaaPostExecute(r RecordCaaAPIRecordcaaPostRequest) (*CreateRecordCaaResponse, *http.Response, error)
	/*
		RecordcaaReferenceDelete Delete a record:caa object

		Deletes a specific record:caa object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the record:caa object
		@return RecordCaaAPIRecordcaaReferenceDeleteRequest
	*/
	RecordcaaReferenceDelete(ctx context.Context, reference string) RecordCaaAPIRecordcaaReferenceDeleteRequest

	// RecordcaaReferenceDeleteExecute executes the request
	RecordcaaReferenceDeleteExecute(r RecordCaaAPIRecordcaaReferenceDeleteRequest) (*http.Response, error)
	/*
		RecordcaaReferenceGet Get a specific record:caa object

		Returns a specific record:caa object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the record:caa object
		@return RecordCaaAPIRecordcaaReferenceGetRequest
	*/
	RecordcaaReferenceGet(ctx context.Context, reference string) RecordCaaAPIRecordcaaReferenceGetRequest

	// RecordcaaReferenceGetExecute executes the request
	//  @return GetRecordCaaResponse
	RecordcaaReferenceGetExecute(r RecordCaaAPIRecordcaaReferenceGetRequest) (*GetRecordCaaResponse, *http.Response, error)
	/*
		RecordcaaReferencePut Update a record:caa object

		Updates a specific record:caa object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the record:caa object
		@return RecordCaaAPIRecordcaaReferencePutRequest
	*/
	RecordcaaReferencePut(ctx context.Context, reference string) RecordCaaAPIRecordcaaReferencePutRequest

	// RecordcaaReferencePutExecute executes the request
	//  @return UpdateRecordCaaResponse
	RecordcaaReferencePutExecute(r RecordCaaAPIRecordcaaReferencePutRequest) (*UpdateRecordCaaResponse, *http.Response, error)
}

// RecordCaaAPIService RecordCaaAPI service
type RecordCaaAPIService internal.Service

type RecordCaaAPIRecordcaaGetRequest struct {
	ctx            context.Context
	ApiService     RecordCaaAPI
	returnFields   *string
	returnFields2  *string
	maxResults     *int32
	returnAsObject *int32
	paging         *int32
	pageId         *string
	filters        *map[string]interface{}
	extattrfilter  *map[string]interface{}
}

// Enter the field names followed by comma
func (r RecordCaaAPIRecordcaaGetRequest) ReturnFields(returnFields string) RecordCaaAPIRecordcaaGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordCaaAPIRecordcaaGetRequest) ReturnFields2(returnFields2 string) RecordCaaAPIRecordcaaGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Enter the number of results to be fetched
func (r RecordCaaAPIRecordcaaGetRequest) MaxResults(maxResults int32) RecordCaaAPIRecordcaaGetRequest {
	r.maxResults = &maxResults
	return r
}

// Select 1 if result is required as an object
func (r RecordCaaAPIRecordcaaGetRequest) ReturnAsObject(returnAsObject int32) RecordCaaAPIRecordcaaGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

// Control paging of results
func (r RecordCaaAPIRecordcaaGetRequest) Paging(paging int32) RecordCaaAPIRecordcaaGetRequest {
	r.paging = &paging
	return r
}

// Page id for retrieving next page of results
func (r RecordCaaAPIRecordcaaGetRequest) PageId(pageId string) RecordCaaAPIRecordcaaGetRequest {
	r.pageId = &pageId
	return r
}

func (r RecordCaaAPIRecordcaaGetRequest) Filters(filters map[string]interface{}) RecordCaaAPIRecordcaaGetRequest {
	r.filters = &filters
	return r
}

func (r RecordCaaAPIRecordcaaGetRequest) Extattrfilter(extattrfilter map[string]interface{}) RecordCaaAPIRecordcaaGetRequest {
	r.extattrfilter = &extattrfilter
	return r
}

func (r RecordCaaAPIRecordcaaGetRequest) Execute() (*ListRecordCaaResponse, *http.Response, error) {
	return r.ApiService.RecordcaaGetExecute(r)
}

/*
RecordcaaGet Retrieve record:caa objects

Returns a list of record:caa objects matching the search criteria

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return RecordCaaAPIRecordcaaGetRequest
*/
func (a *RecordCaaAPIService) RecordcaaGet(ctx context.Context) RecordCaaAPIRecordcaaGetRequest {
	return RecordCaaAPIRecordcaaGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ListRecordCaaResponse
func (a *RecordCaaAPIService) RecordcaaGetExecute(r RecordCaaAPIRecordcaaGetRequest) (*ListRecordCaaResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *ListRecordCaaResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordCaaAPIService.RecordcaaGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:caa"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.maxResults != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_max_results", r.maxResults, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	if r.paging != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_paging", r.paging, "form", "")
	}
	if r.pageId != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_page_id", r.pageId, "form", "")
	}
	if r.filters != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "filters", r.filters, "form", "")
	}
	if r.extattrfilter != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "extattrfilter", r.extattrfilter, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type RecordCaaAPIRecordcaaPostRequest struct {
	ctx            context.Context
	ApiService     RecordCaaAPI
	recordCaa      *RecordCaa
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Object data to create
func (r RecordCaaAPIRecordcaaPostRequest) RecordCaa(recordCaa RecordCaa) RecordCaaAPIRecordcaaPostRequest {
	r.recordCaa = &recordCaa
	return r
}

// Enter the field names followed by comma
func (r RecordCaaAPIRecordcaaPostRequest) ReturnFields(returnFields string) RecordCaaAPIRecordcaaPostRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordCaaAPIRecordcaaPostRequest) ReturnFields2(returnFields2 string) RecordCaaAPIRecordcaaPostRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r RecordCaaAPIRecordcaaPostRequest) ReturnAsObject(returnAsObject int32) RecordCaaAPIRecordcaaPostRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r RecordCaaAPIRecordcaaPostRequest) Execute() (*CreateRecordCaaResponse, *http.Response, error) {
	return r.ApiService.RecordcaaPostExecute(r)
}

/*
RecordcaaPost Create a record:caa object

Creates a new record:caa object

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return RecordCaaAPIRecordcaaPostRequest
*/
func (a *RecordCaaAPIService) RecordcaaPost(ctx context.Context) RecordCaaAPIRecordcaaPostRequest {
	return RecordCaaAPIRecordcaaPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CreateRecordCaaResponse
func (a *RecordCaaAPIService) RecordcaaPostExecute(r RecordCaaAPIRecordcaaPostRequest) (*CreateRecordCaaResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *CreateRecordCaaResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordCaaAPIService.RecordcaaPost")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:caa"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.recordCaa == nil {
		return localVarReturnValue, nil, internal.ReportError("recordCaa is required and must be specified")
	}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if len(a.Client.Cfg.DefaultExtAttrs) > 0 && r.recordCaa != nil {
		if r.recordCaa.Extattrs == nil {
			r.recordCaa.Extattrs = &map[string]ExtAttrs{}
		}
		for k, v := range a.Client.Cfg.DefaultExtAttrs {
			if _, ok := (*r.recordCaa.Extattrs)[k]; !ok {
				(*r.recordCaa.Extattrs)[k] = ExtAttrs{
					Value: v.Value,
				}
			}
		}
	}
	// body params
	localVarPostBody = r.recordCaa
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type RecordCaaAPIRecordcaaReferenceDeleteRequest struct {
	ctx        context.Context
	ApiService RecordCaaAPI
	reference  string
}

func (r RecordCaaAPIRecordcaaReferenceDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.RecordcaaReferenceDeleteExecute(r)
}

/*
RecordcaaReferenceDelete Delete a record:caa object

Deletes a specific record:caa object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the record:caa object
	@return RecordCaaAPIRecordcaaReferenceDeleteRequest
*/
func (a *RecordCaaAPIService) RecordcaaReferenceDelete(ctx context.Context, reference string) RecordCaaAPIRecordcaaReferenceDeleteRequest {
	return RecordCaaAPIRecordcaaReferenceDeleteRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
func (a *RecordCaaAPIService) RecordcaaReferenceDeleteExecute(r RecordCaaAPIRecordcaaReferenceDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []internal.FormFile
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordCaaAPIService.RecordcaaReferenceDelete")
	if err != nil {
		return nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:caa/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type RecordCaaAPIRecordcaaReferenceGetRequest struct {
	ctx            context.Context
	ApiService     RecordCaaAPI
	reference      string
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Enter the field names followed by comma
func (r RecordCaaAPIRecordcaaReferenceGetRequest) ReturnFields(returnFields string) RecordCaaAPIRecordcaaReferenceGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordCaaAPIRecordcaaReferenceGetRequest) ReturnFields2(returnFields2 string) RecordCaaAPIRecordcaaReferenceGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r RecordCaaAPIRecordcaaReferenceGetRequest) ReturnAsObject(returnAsObject int32) RecordCaaAPIRecordcaaReferenceGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r RecordCaaAPIRecordcaaReferenceGetRequest) Execute() (*GetRecordCaaResponse, *http.Response, error) {
	return r.ApiService.RecordcaaReferenceGetExecute(r)
}

/*
RecordcaaReferenceGet Get a specific record:caa object

Returns a specific record:caa object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the record:caa object
	@return RecordCaaAPIRecordcaaReferenceGetRequest
*/
func (a *RecordCaaAPIService) RecordcaaReferenceGet(ctx context.Context, reference string) RecordCaaAPIRecordcaaReferenceGetRequest {
	return RecordCaaAPIRecordcaaReferenceGetRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return GetRecordCaaResponse
func (a *RecordCaaAPIService) RecordcaaReferenceGetExecute(r RecordCaaAPIRecordcaaReferenceGetRequest) (*GetRecordCaaResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *GetRecordCaaResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordCaaAPIService.RecordcaaReferenceGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:caa/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type RecordCaaAPIRecordcaaReferencePutRequest struct {
	ctx            context.Context
	ApiService     RecordCaaAPI
	reference      string
	recordCaa      *RecordCaa
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Object data to update
func (r RecordCaaAPIRecordcaaReferencePutRequest) RecordCaa(recordCaa RecordCaa) RecordCaaAPIRecordcaaReferencePutRequest {
	r.recordCaa = &recordCaa
	return r
}

// Enter the field names followed by comma
func (r RecordCaaAPIRecordcaaReferencePutRequest) ReturnFields(returnFields string) RecordCaaAPIRecordcaaReferencePutRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordCaaAPIRecordcaaReferencePutRequest) ReturnFields2(returnFields2 string) RecordCaaAPIRecordcaaReferencePutRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r RecordCaaAPIRecordcaaReferencePutRequest) ReturnAsObject(returnAsObject int32) RecordCaaAPIRecordcaaReferencePutRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r RecordCaaAPIRecordcaaReferencePutRequest) Execute() (*UpdateRecordCaaResponse, *http.Response, error) {
	return r.ApiService.RecordcaaReferencePutExecute(r)
}

/*
RecordcaaReferencePut Update a record:caa object

Updates a specific record:caa object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the record:caa object
	@return RecordCaaAPIRecordcaaReferencePutRequest
*/
func (a *RecordCaaAPIService) RecordcaaReferencePut(ctx context.Context, reference string) RecordCaaAPIRecordcaaReferencePutRequest {
	return RecordCaaAPIRecordcaaReferencePutRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return UpdateRecordCaaResponse
func (a *RecordCaaAPIService) RecordcaaReferencePutExecute(r RecordCaaAPIRecordcaaReferencePutRequest) (*UpdateRecordCaaResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *UpdateRecordCaaResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordCaaAPIService.RecordcaaReferencePut")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:caa/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.recordCaa == nil {
		return localVarReturnValue, nil, internal.ReportError("recordCaa is required and must be specified")
	}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if len(a.Client.Cfg.DefaultExtAttrs) > 0 && r.recordCaa != nil {
		if r.recordCaa.Extattrs == nil {
			r.recordCaa.Extattrs = &map[string]ExtAttrs{}
		}
		for k, v := range a.Client.Cfg.DefaultExtAttrs {
			if _, ok := (*r.recordCaa.Extattrs)[k]; !ok {
				(*r.recordCaa.Extattrs)[k] = ExtAttrs{
					Value: v.Value,
				}
			}
		}
	}
	// body params
	localVarPostBody = r.recordCaa
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
