/*
Infoblox GRID API

OpenAPI specification for Infoblox NIOS WAPI GRID objects

API version: 2.13.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package grid

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/Infoblox-CTO/infoblox-nios-go-client/internal"
)

type GridThreatprotectionAPI interface {
	/*
		GridthreatprotectionGet Retrieve grid:threatprotection objects

		Returns a list of grid:threatprotection objects matching the search criteria

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return GridThreatprotectionAPIGridthreatprotectionGetRequest
	*/
	GridthreatprotectionGet(ctx context.Context) GridThreatprotectionAPIGridthreatprotectionGetRequest

	// GridthreatprotectionGetExecute executes the request
	//  @return ListGridThreatprotectionResponse
	GridthreatprotectionGetExecute(r GridThreatprotectionAPIGridthreatprotectionGetRequest) (*ListGridThreatprotectionResponse, *http.Response, error)
	/*
		GridthreatprotectionReferenceGet Get a specific grid:threatprotection object

		Returns a specific grid:threatprotection object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the grid:threatprotection object
		@return GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest
	*/
	GridthreatprotectionReferenceGet(ctx context.Context, reference string) GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest

	// GridthreatprotectionReferenceGetExecute executes the request
	//  @return GetGridThreatprotectionResponse
	GridthreatprotectionReferenceGetExecute(r GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest) (*GetGridThreatprotectionResponse, *http.Response, error)
	/*
		GridthreatprotectionReferencePut Update a grid:threatprotection object

		Updates a specific grid:threatprotection object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the grid:threatprotection object
		@return GridThreatprotectionAPIGridthreatprotectionReferencePutRequest
	*/
	GridthreatprotectionReferencePut(ctx context.Context, reference string) GridThreatprotectionAPIGridthreatprotectionReferencePutRequest

	// GridthreatprotectionReferencePutExecute executes the request
	//  @return UpdateGridThreatprotectionResponse
	GridthreatprotectionReferencePutExecute(r GridThreatprotectionAPIGridthreatprotectionReferencePutRequest) (*UpdateGridThreatprotectionResponse, *http.Response, error)
}

// GridThreatprotectionAPIService GridThreatprotectionAPI service
type GridThreatprotectionAPIService internal.Service

type GridThreatprotectionAPIGridthreatprotectionGetRequest struct {
	ctx            context.Context
	ApiService     GridThreatprotectionAPI
	returnFields   *string
	returnFields2  *string
	maxResults     *int32
	returnAsObject *int32
	paging         *int32
	pageId         *string
	filters        *map[string]interface{}
	extattrfilter  *map[string]interface{}
}

// Enter the field names followed by comma
func (r GridThreatprotectionAPIGridthreatprotectionGetRequest) ReturnFields(returnFields string) GridThreatprotectionAPIGridthreatprotectionGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r GridThreatprotectionAPIGridthreatprotectionGetRequest) ReturnFields2(returnFields2 string) GridThreatprotectionAPIGridthreatprotectionGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Enter the number of results to be fetched
func (r GridThreatprotectionAPIGridthreatprotectionGetRequest) MaxResults(maxResults int32) GridThreatprotectionAPIGridthreatprotectionGetRequest {
	r.maxResults = &maxResults
	return r
}

// Select 1 if result is required as an object
func (r GridThreatprotectionAPIGridthreatprotectionGetRequest) ReturnAsObject(returnAsObject int32) GridThreatprotectionAPIGridthreatprotectionGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

// Control paging of results
func (r GridThreatprotectionAPIGridthreatprotectionGetRequest) Paging(paging int32) GridThreatprotectionAPIGridthreatprotectionGetRequest {
	r.paging = &paging
	return r
}

// Page id for retrieving next page of results
func (r GridThreatprotectionAPIGridthreatprotectionGetRequest) PageId(pageId string) GridThreatprotectionAPIGridthreatprotectionGetRequest {
	r.pageId = &pageId
	return r
}

func (r GridThreatprotectionAPIGridthreatprotectionGetRequest) Filters(filters map[string]interface{}) GridThreatprotectionAPIGridthreatprotectionGetRequest {
	r.filters = &filters
	return r
}

func (r GridThreatprotectionAPIGridthreatprotectionGetRequest) Extattrfilter(extattrfilter map[string]interface{}) GridThreatprotectionAPIGridthreatprotectionGetRequest {
	r.extattrfilter = &extattrfilter
	return r
}

func (r GridThreatprotectionAPIGridthreatprotectionGetRequest) Execute() (*ListGridThreatprotectionResponse, *http.Response, error) {
	return r.ApiService.GridthreatprotectionGetExecute(r)
}

/*
GridthreatprotectionGet Retrieve grid:threatprotection objects

Returns a list of grid:threatprotection objects matching the search criteria

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return GridThreatprotectionAPIGridthreatprotectionGetRequest
*/
func (a *GridThreatprotectionAPIService) GridthreatprotectionGet(ctx context.Context) GridThreatprotectionAPIGridthreatprotectionGetRequest {
	return GridThreatprotectionAPIGridthreatprotectionGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ListGridThreatprotectionResponse
func (a *GridThreatprotectionAPIService) GridthreatprotectionGetExecute(r GridThreatprotectionAPIGridthreatprotectionGetRequest) (*ListGridThreatprotectionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *ListGridThreatprotectionResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "GridThreatprotectionAPIService.GridthreatprotectionGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/grid:threatprotection"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.maxResults != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_max_results", r.maxResults, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	if r.paging != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_paging", r.paging, "form", "")
	}
	if r.pageId != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_page_id", r.pageId, "form", "")
	}
	if r.filters != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "filters", r.filters, "form", "")
	}
	if r.extattrfilter != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "extattrfilter", r.extattrfilter, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest struct {
	ctx            context.Context
	ApiService     GridThreatprotectionAPI
	reference      string
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Enter the field names followed by comma
func (r GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest) ReturnFields(returnFields string) GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest) ReturnFields2(returnFields2 string) GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest) ReturnAsObject(returnAsObject int32) GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest) Execute() (*GetGridThreatprotectionResponse, *http.Response, error) {
	return r.ApiService.GridthreatprotectionReferenceGetExecute(r)
}

/*
GridthreatprotectionReferenceGet Get a specific grid:threatprotection object

Returns a specific grid:threatprotection object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the grid:threatprotection object
	@return GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest
*/
func (a *GridThreatprotectionAPIService) GridthreatprotectionReferenceGet(ctx context.Context, reference string) GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest {
	return GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return GetGridThreatprotectionResponse
func (a *GridThreatprotectionAPIService) GridthreatprotectionReferenceGetExecute(r GridThreatprotectionAPIGridthreatprotectionReferenceGetRequest) (*GetGridThreatprotectionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *GetGridThreatprotectionResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "GridThreatprotectionAPIService.GridthreatprotectionReferenceGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/grid:threatprotection/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type GridThreatprotectionAPIGridthreatprotectionReferencePutRequest struct {
	ctx                  context.Context
	ApiService           GridThreatprotectionAPI
	reference            string
	gridThreatprotection *GridThreatprotection
	returnFields         *string
	returnFields2        *string
	returnAsObject       *int32
}

// Object data to update
func (r GridThreatprotectionAPIGridthreatprotectionReferencePutRequest) GridThreatprotection(gridThreatprotection GridThreatprotection) GridThreatprotectionAPIGridthreatprotectionReferencePutRequest {
	r.gridThreatprotection = &gridThreatprotection
	return r
}

// Enter the field names followed by comma
func (r GridThreatprotectionAPIGridthreatprotectionReferencePutRequest) ReturnFields(returnFields string) GridThreatprotectionAPIGridthreatprotectionReferencePutRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r GridThreatprotectionAPIGridthreatprotectionReferencePutRequest) ReturnFields2(returnFields2 string) GridThreatprotectionAPIGridthreatprotectionReferencePutRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r GridThreatprotectionAPIGridthreatprotectionReferencePutRequest) ReturnAsObject(returnAsObject int32) GridThreatprotectionAPIGridthreatprotectionReferencePutRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r GridThreatprotectionAPIGridthreatprotectionReferencePutRequest) Execute() (*UpdateGridThreatprotectionResponse, *http.Response, error) {
	return r.ApiService.GridthreatprotectionReferencePutExecute(r)
}

/*
GridthreatprotectionReferencePut Update a grid:threatprotection object

Updates a specific grid:threatprotection object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the grid:threatprotection object
	@return GridThreatprotectionAPIGridthreatprotectionReferencePutRequest
*/
func (a *GridThreatprotectionAPIService) GridthreatprotectionReferencePut(ctx context.Context, reference string) GridThreatprotectionAPIGridthreatprotectionReferencePutRequest {
	return GridThreatprotectionAPIGridthreatprotectionReferencePutRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return UpdateGridThreatprotectionResponse
func (a *GridThreatprotectionAPIService) GridthreatprotectionReferencePutExecute(r GridThreatprotectionAPIGridthreatprotectionReferencePutRequest) (*UpdateGridThreatprotectionResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *UpdateGridThreatprotectionResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "GridThreatprotectionAPIService.GridthreatprotectionReferencePut")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/grid:threatprotection/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.gridThreatprotection == nil {
		return localVarReturnValue, nil, internal.ReportError("gridThreatprotection is required and must be specified")
	}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.gridThreatprotection
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
