/*
Infoblox RPZ API

OpenAPI specification for Infoblox NIOS WAPI RPZ objects

API version: 2.13.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rpz

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/Infoblox-CTO/infoblox-nios-go-client/internal"
)

type RecordRpzPtrAPI interface {
	/*
		RecordrpzptrGet Retrieve record:rpz:ptr objects

		Returns a list of record:rpz:ptr objects matching the search criteria

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return RecordRpzPtrAPIRecordrpzptrGetRequest
	*/
	RecordrpzptrGet(ctx context.Context) RecordRpzPtrAPIRecordrpzptrGetRequest

	// RecordrpzptrGetExecute executes the request
	//  @return ListRecordRpzPtrResponse
	RecordrpzptrGetExecute(r RecordRpzPtrAPIRecordrpzptrGetRequest) (*ListRecordRpzPtrResponse, *http.Response, error)
	/*
		RecordrpzptrPost Create a record:rpz:ptr object

		Creates a new record:rpz:ptr object

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return RecordRpzPtrAPIRecordrpzptrPostRequest
	*/
	RecordrpzptrPost(ctx context.Context) RecordRpzPtrAPIRecordrpzptrPostRequest

	// RecordrpzptrPostExecute executes the request
	//  @return CreateRecordRpzPtrResponse
	RecordrpzptrPostExecute(r RecordRpzPtrAPIRecordrpzptrPostRequest) (*CreateRecordRpzPtrResponse, *http.Response, error)
	/*
		RecordrpzptrReferenceDelete Delete a record:rpz:ptr object

		Deletes a specific record:rpz:ptr object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the record:rpz:ptr object
		@return RecordRpzPtrAPIRecordrpzptrReferenceDeleteRequest
	*/
	RecordrpzptrReferenceDelete(ctx context.Context, reference string) RecordRpzPtrAPIRecordrpzptrReferenceDeleteRequest

	// RecordrpzptrReferenceDeleteExecute executes the request
	RecordrpzptrReferenceDeleteExecute(r RecordRpzPtrAPIRecordrpzptrReferenceDeleteRequest) (*http.Response, error)
	/*
		RecordrpzptrReferenceGet Get a specific record:rpz:ptr object

		Returns a specific record:rpz:ptr object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the record:rpz:ptr object
		@return RecordRpzPtrAPIRecordrpzptrReferenceGetRequest
	*/
	RecordrpzptrReferenceGet(ctx context.Context, reference string) RecordRpzPtrAPIRecordrpzptrReferenceGetRequest

	// RecordrpzptrReferenceGetExecute executes the request
	//  @return GetRecordRpzPtrResponse
	RecordrpzptrReferenceGetExecute(r RecordRpzPtrAPIRecordrpzptrReferenceGetRequest) (*GetRecordRpzPtrResponse, *http.Response, error)
	/*
		RecordrpzptrReferencePut Update a record:rpz:ptr object

		Updates a specific record:rpz:ptr object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the record:rpz:ptr object
		@return RecordRpzPtrAPIRecordrpzptrReferencePutRequest
	*/
	RecordrpzptrReferencePut(ctx context.Context, reference string) RecordRpzPtrAPIRecordrpzptrReferencePutRequest

	// RecordrpzptrReferencePutExecute executes the request
	//  @return UpdateRecordRpzPtrResponse
	RecordrpzptrReferencePutExecute(r RecordRpzPtrAPIRecordrpzptrReferencePutRequest) (*UpdateRecordRpzPtrResponse, *http.Response, error)
}

// RecordRpzPtrAPIService RecordRpzPtrAPI service
type RecordRpzPtrAPIService internal.Service

type RecordRpzPtrAPIRecordrpzptrGetRequest struct {
	ctx            context.Context
	ApiService     RecordRpzPtrAPI
	returnFields   *string
	returnFields2  *string
	maxResults     *int32
	returnAsObject *int32
	paging         *int32
	pageId         *string
	filters        *map[string]interface{}
	extattrfilter  *map[string]interface{}
}

// Enter the field names followed by comma
func (r RecordRpzPtrAPIRecordrpzptrGetRequest) ReturnFields(returnFields string) RecordRpzPtrAPIRecordrpzptrGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordRpzPtrAPIRecordrpzptrGetRequest) ReturnFields2(returnFields2 string) RecordRpzPtrAPIRecordrpzptrGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Enter the number of results to be fetched
func (r RecordRpzPtrAPIRecordrpzptrGetRequest) MaxResults(maxResults int32) RecordRpzPtrAPIRecordrpzptrGetRequest {
	r.maxResults = &maxResults
	return r
}

// Select 1 if result is required as an object
func (r RecordRpzPtrAPIRecordrpzptrGetRequest) ReturnAsObject(returnAsObject int32) RecordRpzPtrAPIRecordrpzptrGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

// Control paging of results
func (r RecordRpzPtrAPIRecordrpzptrGetRequest) Paging(paging int32) RecordRpzPtrAPIRecordrpzptrGetRequest {
	r.paging = &paging
	return r
}

// Page id for retrieving next page of results
func (r RecordRpzPtrAPIRecordrpzptrGetRequest) PageId(pageId string) RecordRpzPtrAPIRecordrpzptrGetRequest {
	r.pageId = &pageId
	return r
}

func (r RecordRpzPtrAPIRecordrpzptrGetRequest) Filters(filters map[string]interface{}) RecordRpzPtrAPIRecordrpzptrGetRequest {
	r.filters = &filters
	return r
}

func (r RecordRpzPtrAPIRecordrpzptrGetRequest) Extattrfilter(extattrfilter map[string]interface{}) RecordRpzPtrAPIRecordrpzptrGetRequest {
	r.extattrfilter = &extattrfilter
	return r
}

func (r RecordRpzPtrAPIRecordrpzptrGetRequest) Execute() (*ListRecordRpzPtrResponse, *http.Response, error) {
	return r.ApiService.RecordrpzptrGetExecute(r)
}

/*
RecordrpzptrGet Retrieve record:rpz:ptr objects

Returns a list of record:rpz:ptr objects matching the search criteria

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return RecordRpzPtrAPIRecordrpzptrGetRequest
*/
func (a *RecordRpzPtrAPIService) RecordrpzptrGet(ctx context.Context) RecordRpzPtrAPIRecordrpzptrGetRequest {
	return RecordRpzPtrAPIRecordrpzptrGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ListRecordRpzPtrResponse
func (a *RecordRpzPtrAPIService) RecordrpzptrGetExecute(r RecordRpzPtrAPIRecordrpzptrGetRequest) (*ListRecordRpzPtrResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *ListRecordRpzPtrResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordRpzPtrAPIService.RecordrpzptrGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:rpz:ptr"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.maxResults != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_max_results", r.maxResults, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	if r.paging != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_paging", r.paging, "form", "")
	}
	if r.pageId != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_page_id", r.pageId, "form", "")
	}
	if r.filters != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "filters", r.filters, "form", "")
	}
	if r.extattrfilter != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "extattrfilter", r.extattrfilter, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type RecordRpzPtrAPIRecordrpzptrPostRequest struct {
	ctx            context.Context
	ApiService     RecordRpzPtrAPI
	recordRpzPtr   *RecordRpzPtr
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Object data to create
func (r RecordRpzPtrAPIRecordrpzptrPostRequest) RecordRpzPtr(recordRpzPtr RecordRpzPtr) RecordRpzPtrAPIRecordrpzptrPostRequest {
	r.recordRpzPtr = &recordRpzPtr
	return r
}

// Enter the field names followed by comma
func (r RecordRpzPtrAPIRecordrpzptrPostRequest) ReturnFields(returnFields string) RecordRpzPtrAPIRecordrpzptrPostRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordRpzPtrAPIRecordrpzptrPostRequest) ReturnFields2(returnFields2 string) RecordRpzPtrAPIRecordrpzptrPostRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r RecordRpzPtrAPIRecordrpzptrPostRequest) ReturnAsObject(returnAsObject int32) RecordRpzPtrAPIRecordrpzptrPostRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r RecordRpzPtrAPIRecordrpzptrPostRequest) Execute() (*CreateRecordRpzPtrResponse, *http.Response, error) {
	return r.ApiService.RecordrpzptrPostExecute(r)
}

/*
RecordrpzptrPost Create a record:rpz:ptr object

Creates a new record:rpz:ptr object

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return RecordRpzPtrAPIRecordrpzptrPostRequest
*/
func (a *RecordRpzPtrAPIService) RecordrpzptrPost(ctx context.Context) RecordRpzPtrAPIRecordrpzptrPostRequest {
	return RecordRpzPtrAPIRecordrpzptrPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CreateRecordRpzPtrResponse
func (a *RecordRpzPtrAPIService) RecordrpzptrPostExecute(r RecordRpzPtrAPIRecordrpzptrPostRequest) (*CreateRecordRpzPtrResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *CreateRecordRpzPtrResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordRpzPtrAPIService.RecordrpzptrPost")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:rpz:ptr"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.recordRpzPtr == nil {
		return localVarReturnValue, nil, internal.ReportError("recordRpzPtr is required and must be specified")
	}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if len(a.Client.Cfg.DefaultExtAttrs) > 0 && r.recordRpzPtr != nil {
		if r.recordRpzPtr.Extattrs == nil {
			r.recordRpzPtr.Extattrs = &map[string]ExtAttrs{}
		}
		for k, v := range a.Client.Cfg.DefaultExtAttrs {
			if _, ok := (*r.recordRpzPtr.Extattrs)[k]; !ok {
				(*r.recordRpzPtr.Extattrs)[k] = ExtAttrs{
					Value: v.Value,
				}
			}
		}
	}
	// body params
	localVarPostBody = r.recordRpzPtr
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type RecordRpzPtrAPIRecordrpzptrReferenceDeleteRequest struct {
	ctx        context.Context
	ApiService RecordRpzPtrAPI
	reference  string
}

func (r RecordRpzPtrAPIRecordrpzptrReferenceDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.RecordrpzptrReferenceDeleteExecute(r)
}

/*
RecordrpzptrReferenceDelete Delete a record:rpz:ptr object

Deletes a specific record:rpz:ptr object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the record:rpz:ptr object
	@return RecordRpzPtrAPIRecordrpzptrReferenceDeleteRequest
*/
func (a *RecordRpzPtrAPIService) RecordrpzptrReferenceDelete(ctx context.Context, reference string) RecordRpzPtrAPIRecordrpzptrReferenceDeleteRequest {
	return RecordRpzPtrAPIRecordrpzptrReferenceDeleteRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
func (a *RecordRpzPtrAPIService) RecordrpzptrReferenceDeleteExecute(r RecordRpzPtrAPIRecordrpzptrReferenceDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []internal.FormFile
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordRpzPtrAPIService.RecordrpzptrReferenceDelete")
	if err != nil {
		return nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:rpz:ptr/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type RecordRpzPtrAPIRecordrpzptrReferenceGetRequest struct {
	ctx            context.Context
	ApiService     RecordRpzPtrAPI
	reference      string
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Enter the field names followed by comma
func (r RecordRpzPtrAPIRecordrpzptrReferenceGetRequest) ReturnFields(returnFields string) RecordRpzPtrAPIRecordrpzptrReferenceGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordRpzPtrAPIRecordrpzptrReferenceGetRequest) ReturnFields2(returnFields2 string) RecordRpzPtrAPIRecordrpzptrReferenceGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r RecordRpzPtrAPIRecordrpzptrReferenceGetRequest) ReturnAsObject(returnAsObject int32) RecordRpzPtrAPIRecordrpzptrReferenceGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r RecordRpzPtrAPIRecordrpzptrReferenceGetRequest) Execute() (*GetRecordRpzPtrResponse, *http.Response, error) {
	return r.ApiService.RecordrpzptrReferenceGetExecute(r)
}

/*
RecordrpzptrReferenceGet Get a specific record:rpz:ptr object

Returns a specific record:rpz:ptr object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the record:rpz:ptr object
	@return RecordRpzPtrAPIRecordrpzptrReferenceGetRequest
*/
func (a *RecordRpzPtrAPIService) RecordrpzptrReferenceGet(ctx context.Context, reference string) RecordRpzPtrAPIRecordrpzptrReferenceGetRequest {
	return RecordRpzPtrAPIRecordrpzptrReferenceGetRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return GetRecordRpzPtrResponse
func (a *RecordRpzPtrAPIService) RecordrpzptrReferenceGetExecute(r RecordRpzPtrAPIRecordrpzptrReferenceGetRequest) (*GetRecordRpzPtrResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *GetRecordRpzPtrResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordRpzPtrAPIService.RecordrpzptrReferenceGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:rpz:ptr/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type RecordRpzPtrAPIRecordrpzptrReferencePutRequest struct {
	ctx            context.Context
	ApiService     RecordRpzPtrAPI
	reference      string
	recordRpzPtr   *RecordRpzPtr
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Object data to update
func (r RecordRpzPtrAPIRecordrpzptrReferencePutRequest) RecordRpzPtr(recordRpzPtr RecordRpzPtr) RecordRpzPtrAPIRecordrpzptrReferencePutRequest {
	r.recordRpzPtr = &recordRpzPtr
	return r
}

// Enter the field names followed by comma
func (r RecordRpzPtrAPIRecordrpzptrReferencePutRequest) ReturnFields(returnFields string) RecordRpzPtrAPIRecordrpzptrReferencePutRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r RecordRpzPtrAPIRecordrpzptrReferencePutRequest) ReturnFields2(returnFields2 string) RecordRpzPtrAPIRecordrpzptrReferencePutRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r RecordRpzPtrAPIRecordrpzptrReferencePutRequest) ReturnAsObject(returnAsObject int32) RecordRpzPtrAPIRecordrpzptrReferencePutRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r RecordRpzPtrAPIRecordrpzptrReferencePutRequest) Execute() (*UpdateRecordRpzPtrResponse, *http.Response, error) {
	return r.ApiService.RecordrpzptrReferencePutExecute(r)
}

/*
RecordrpzptrReferencePut Update a record:rpz:ptr object

Updates a specific record:rpz:ptr object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the record:rpz:ptr object
	@return RecordRpzPtrAPIRecordrpzptrReferencePutRequest
*/
func (a *RecordRpzPtrAPIService) RecordrpzptrReferencePut(ctx context.Context, reference string) RecordRpzPtrAPIRecordrpzptrReferencePutRequest {
	return RecordRpzPtrAPIRecordrpzptrReferencePutRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return UpdateRecordRpzPtrResponse
func (a *RecordRpzPtrAPIService) RecordrpzptrReferencePutExecute(r RecordRpzPtrAPIRecordrpzptrReferencePutRequest) (*UpdateRecordRpzPtrResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *UpdateRecordRpzPtrResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "RecordRpzPtrAPIService.RecordrpzptrReferencePut")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/record:rpz:ptr/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.recordRpzPtr == nil {
		return localVarReturnValue, nil, internal.ReportError("recordRpzPtr is required and must be specified")
	}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if len(a.Client.Cfg.DefaultExtAttrs) > 0 && r.recordRpzPtr != nil {
		if r.recordRpzPtr.Extattrs == nil {
			r.recordRpzPtr.Extattrs = &map[string]ExtAttrs{}
		}
		for k, v := range a.Client.Cfg.DefaultExtAttrs {
			if _, ok := (*r.recordRpzPtr.Extattrs)[k]; !ok {
				(*r.recordRpzPtr.Extattrs)[k] = ExtAttrs{
					Value: v.Value,
				}
			}
		}
	}
	// body params
	localVarPostBody = r.recordRpzPtr
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
