/*
Infoblox DTC API

OpenAPI specification for Infoblox NIOS WAPI DTC objects

API version: 2.13.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dtc

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/Infoblox-CTO/infoblox-nios-go-client/internal"
)

type DtcMonitorAPI interface {
	/*
		DtcmonitorGet Retrieve dtc:monitor objects

		Returns a list of dtc:monitor objects matching the search criteria

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return DtcMonitorAPIDtcmonitorGetRequest
	*/
	DtcmonitorGet(ctx context.Context) DtcMonitorAPIDtcmonitorGetRequest

	// DtcmonitorGetExecute executes the request
	//  @return ListDtcMonitorResponse
	DtcmonitorGetExecute(r DtcMonitorAPIDtcmonitorGetRequest) (*ListDtcMonitorResponse, *http.Response, error)
	/*
		DtcmonitorReferenceGet Get a specific dtc:monitor object

		Returns a specific dtc:monitor object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the dtc:monitor object
		@return DtcMonitorAPIDtcmonitorReferenceGetRequest
	*/
	DtcmonitorReferenceGet(ctx context.Context, reference string) DtcMonitorAPIDtcmonitorReferenceGetRequest

	// DtcmonitorReferenceGetExecute executes the request
	//  @return GetDtcMonitorResponse
	DtcmonitorReferenceGetExecute(r DtcMonitorAPIDtcmonitorReferenceGetRequest) (*GetDtcMonitorResponse, *http.Response, error)
	/*
		DtcmonitorReferencePut Update a dtc:monitor object

		Updates a specific dtc:monitor object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the dtc:monitor object
		@return DtcMonitorAPIDtcmonitorReferencePutRequest
	*/
	DtcmonitorReferencePut(ctx context.Context, reference string) DtcMonitorAPIDtcmonitorReferencePutRequest

	// DtcmonitorReferencePutExecute executes the request
	//  @return UpdateDtcMonitorResponse
	DtcmonitorReferencePutExecute(r DtcMonitorAPIDtcmonitorReferencePutRequest) (*UpdateDtcMonitorResponse, *http.Response, error)
}

// DtcMonitorAPIService DtcMonitorAPI service
type DtcMonitorAPIService internal.Service

type DtcMonitorAPIDtcmonitorGetRequest struct {
	ctx            context.Context
	ApiService     DtcMonitorAPI
	returnFields   *string
	returnFields2  *string
	maxResults     *int32
	returnAsObject *int32
	paging         *int32
	pageId         *string
	filters        *map[string]interface{}
	extattrfilter  *map[string]interface{}
}

// Enter the field names followed by comma
func (r DtcMonitorAPIDtcmonitorGetRequest) ReturnFields(returnFields string) DtcMonitorAPIDtcmonitorGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r DtcMonitorAPIDtcmonitorGetRequest) ReturnFields2(returnFields2 string) DtcMonitorAPIDtcmonitorGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Enter the number of results to be fetched
func (r DtcMonitorAPIDtcmonitorGetRequest) MaxResults(maxResults int32) DtcMonitorAPIDtcmonitorGetRequest {
	r.maxResults = &maxResults
	return r
}

// Select 1 if result is required as an object
func (r DtcMonitorAPIDtcmonitorGetRequest) ReturnAsObject(returnAsObject int32) DtcMonitorAPIDtcmonitorGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

// Control paging of results
func (r DtcMonitorAPIDtcmonitorGetRequest) Paging(paging int32) DtcMonitorAPIDtcmonitorGetRequest {
	r.paging = &paging
	return r
}

// Page id for retrieving next page of results
func (r DtcMonitorAPIDtcmonitorGetRequest) PageId(pageId string) DtcMonitorAPIDtcmonitorGetRequest {
	r.pageId = &pageId
	return r
}

func (r DtcMonitorAPIDtcmonitorGetRequest) Filters(filters map[string]interface{}) DtcMonitorAPIDtcmonitorGetRequest {
	r.filters = &filters
	return r
}

func (r DtcMonitorAPIDtcmonitorGetRequest) Extattrfilter(extattrfilter map[string]interface{}) DtcMonitorAPIDtcmonitorGetRequest {
	r.extattrfilter = &extattrfilter
	return r
}

func (r DtcMonitorAPIDtcmonitorGetRequest) Execute() (*ListDtcMonitorResponse, *http.Response, error) {
	return r.ApiService.DtcmonitorGetExecute(r)
}

/*
DtcmonitorGet Retrieve dtc:monitor objects

Returns a list of dtc:monitor objects matching the search criteria

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DtcMonitorAPIDtcmonitorGetRequest
*/
func (a *DtcMonitorAPIService) DtcmonitorGet(ctx context.Context) DtcMonitorAPIDtcmonitorGetRequest {
	return DtcMonitorAPIDtcmonitorGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ListDtcMonitorResponse
func (a *DtcMonitorAPIService) DtcmonitorGetExecute(r DtcMonitorAPIDtcmonitorGetRequest) (*ListDtcMonitorResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *ListDtcMonitorResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "DtcMonitorAPIService.DtcmonitorGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/dtc:monitor"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.maxResults != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_max_results", r.maxResults, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	if r.paging != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_paging", r.paging, "form", "")
	}
	if r.pageId != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_page_id", r.pageId, "form", "")
	}
	if r.filters != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "filters", r.filters, "form", "")
	}
	if r.extattrfilter != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "extattrfilter", r.extattrfilter, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type DtcMonitorAPIDtcmonitorReferenceGetRequest struct {
	ctx            context.Context
	ApiService     DtcMonitorAPI
	reference      string
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Enter the field names followed by comma
func (r DtcMonitorAPIDtcmonitorReferenceGetRequest) ReturnFields(returnFields string) DtcMonitorAPIDtcmonitorReferenceGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r DtcMonitorAPIDtcmonitorReferenceGetRequest) ReturnFields2(returnFields2 string) DtcMonitorAPIDtcmonitorReferenceGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r DtcMonitorAPIDtcmonitorReferenceGetRequest) ReturnAsObject(returnAsObject int32) DtcMonitorAPIDtcmonitorReferenceGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r DtcMonitorAPIDtcmonitorReferenceGetRequest) Execute() (*GetDtcMonitorResponse, *http.Response, error) {
	return r.ApiService.DtcmonitorReferenceGetExecute(r)
}

/*
DtcmonitorReferenceGet Get a specific dtc:monitor object

Returns a specific dtc:monitor object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the dtc:monitor object
	@return DtcMonitorAPIDtcmonitorReferenceGetRequest
*/
func (a *DtcMonitorAPIService) DtcmonitorReferenceGet(ctx context.Context, reference string) DtcMonitorAPIDtcmonitorReferenceGetRequest {
	return DtcMonitorAPIDtcmonitorReferenceGetRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return GetDtcMonitorResponse
func (a *DtcMonitorAPIService) DtcmonitorReferenceGetExecute(r DtcMonitorAPIDtcmonitorReferenceGetRequest) (*GetDtcMonitorResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *GetDtcMonitorResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "DtcMonitorAPIService.DtcmonitorReferenceGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/dtc:monitor/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type DtcMonitorAPIDtcmonitorReferencePutRequest struct {
	ctx            context.Context
	ApiService     DtcMonitorAPI
	reference      string
	dtcMonitor     *DtcMonitor
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Object data to update
func (r DtcMonitorAPIDtcmonitorReferencePutRequest) DtcMonitor(dtcMonitor DtcMonitor) DtcMonitorAPIDtcmonitorReferencePutRequest {
	r.dtcMonitor = &dtcMonitor
	return r
}

// Enter the field names followed by comma
func (r DtcMonitorAPIDtcmonitorReferencePutRequest) ReturnFields(returnFields string) DtcMonitorAPIDtcmonitorReferencePutRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r DtcMonitorAPIDtcmonitorReferencePutRequest) ReturnFields2(returnFields2 string) DtcMonitorAPIDtcmonitorReferencePutRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r DtcMonitorAPIDtcmonitorReferencePutRequest) ReturnAsObject(returnAsObject int32) DtcMonitorAPIDtcmonitorReferencePutRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r DtcMonitorAPIDtcmonitorReferencePutRequest) Execute() (*UpdateDtcMonitorResponse, *http.Response, error) {
	return r.ApiService.DtcmonitorReferencePutExecute(r)
}

/*
DtcmonitorReferencePut Update a dtc:monitor object

Updates a specific dtc:monitor object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the dtc:monitor object
	@return DtcMonitorAPIDtcmonitorReferencePutRequest
*/
func (a *DtcMonitorAPIService) DtcmonitorReferencePut(ctx context.Context, reference string) DtcMonitorAPIDtcmonitorReferencePutRequest {
	return DtcMonitorAPIDtcmonitorReferencePutRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return UpdateDtcMonitorResponse
func (a *DtcMonitorAPIService) DtcmonitorReferencePutExecute(r DtcMonitorAPIDtcmonitorReferencePutRequest) (*UpdateDtcMonitorResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *UpdateDtcMonitorResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "DtcMonitorAPIService.DtcmonitorReferencePut")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/dtc:monitor/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.dtcMonitor == nil {
		return localVarReturnValue, nil, internal.ReportError("dtcMonitor is required and must be specified")
	}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if len(a.Client.Cfg.DefaultExtAttrs) > 0 && r.dtcMonitor != nil {
		if r.dtcMonitor.Extattrs == nil {
			r.dtcMonitor.Extattrs = &map[string]ExtAttrs{}
		}
		for k, v := range a.Client.Cfg.DefaultExtAttrs {
			if _, ok := (*r.dtcMonitor.Extattrs)[k]; !ok {
				(*r.dtcMonitor.Extattrs)[k] = ExtAttrs{
					Value: v.Value,
				}
			}
		}
	}
	// body params
	localVarPostBody = r.dtcMonitor
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
