/*
Infoblox DISCOVERY API

OpenAPI specification for Infoblox NIOS WAPI DISCOVERY objects

API version: 2.13.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discovery

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/Infoblox-CTO/infoblox-nios-go-client/internal"
)

type DiscoveryStatusAPI interface {
	/*
		DiscoverystatusGet Retrieve discovery:status objects

		Returns a list of discovery:status objects matching the search criteria

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return DiscoveryStatusAPIDiscoverystatusGetRequest
	*/
	DiscoverystatusGet(ctx context.Context) DiscoveryStatusAPIDiscoverystatusGetRequest

	// DiscoverystatusGetExecute executes the request
	//  @return ListDiscoveryStatusResponse
	DiscoverystatusGetExecute(r DiscoveryStatusAPIDiscoverystatusGetRequest) (*ListDiscoveryStatusResponse, *http.Response, error)
	/*
		DiscoverystatusReferenceGet Get a specific discovery:status object

		Returns a specific discovery:status object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the discovery:status object
		@return DiscoveryStatusAPIDiscoverystatusReferenceGetRequest
	*/
	DiscoverystatusReferenceGet(ctx context.Context, reference string) DiscoveryStatusAPIDiscoverystatusReferenceGetRequest

	// DiscoverystatusReferenceGetExecute executes the request
	//  @return GetDiscoveryStatusResponse
	DiscoverystatusReferenceGetExecute(r DiscoveryStatusAPIDiscoverystatusReferenceGetRequest) (*GetDiscoveryStatusResponse, *http.Response, error)
}

// DiscoveryStatusAPIService DiscoveryStatusAPI service
type DiscoveryStatusAPIService internal.Service

type DiscoveryStatusAPIDiscoverystatusGetRequest struct {
	ctx            context.Context
	ApiService     DiscoveryStatusAPI
	returnFields   *string
	returnFields2  *string
	maxResults     *int32
	returnAsObject *int32
	paging         *int32
	pageId         *string
	filters        *map[string]interface{}
	extattrfilter  *map[string]interface{}
}

// Enter the field names followed by comma
func (r DiscoveryStatusAPIDiscoverystatusGetRequest) ReturnFields(returnFields string) DiscoveryStatusAPIDiscoverystatusGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r DiscoveryStatusAPIDiscoverystatusGetRequest) ReturnFields2(returnFields2 string) DiscoveryStatusAPIDiscoverystatusGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Enter the number of results to be fetched
func (r DiscoveryStatusAPIDiscoverystatusGetRequest) MaxResults(maxResults int32) DiscoveryStatusAPIDiscoverystatusGetRequest {
	r.maxResults = &maxResults
	return r
}

// Select 1 if result is required as an object
func (r DiscoveryStatusAPIDiscoverystatusGetRequest) ReturnAsObject(returnAsObject int32) DiscoveryStatusAPIDiscoverystatusGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

// Control paging of results
func (r DiscoveryStatusAPIDiscoverystatusGetRequest) Paging(paging int32) DiscoveryStatusAPIDiscoverystatusGetRequest {
	r.paging = &paging
	return r
}

// Page id for retrieving next page of results
func (r DiscoveryStatusAPIDiscoverystatusGetRequest) PageId(pageId string) DiscoveryStatusAPIDiscoverystatusGetRequest {
	r.pageId = &pageId
	return r
}

func (r DiscoveryStatusAPIDiscoverystatusGetRequest) Filters(filters map[string]interface{}) DiscoveryStatusAPIDiscoverystatusGetRequest {
	r.filters = &filters
	return r
}

func (r DiscoveryStatusAPIDiscoverystatusGetRequest) Extattrfilter(extattrfilter map[string]interface{}) DiscoveryStatusAPIDiscoverystatusGetRequest {
	r.extattrfilter = &extattrfilter
	return r
}

func (r DiscoveryStatusAPIDiscoverystatusGetRequest) Execute() (*ListDiscoveryStatusResponse, *http.Response, error) {
	return r.ApiService.DiscoverystatusGetExecute(r)
}

/*
DiscoverystatusGet Retrieve discovery:status objects

Returns a list of discovery:status objects matching the search criteria

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return DiscoveryStatusAPIDiscoverystatusGetRequest
*/
func (a *DiscoveryStatusAPIService) DiscoverystatusGet(ctx context.Context) DiscoveryStatusAPIDiscoverystatusGetRequest {
	return DiscoveryStatusAPIDiscoverystatusGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ListDiscoveryStatusResponse
func (a *DiscoveryStatusAPIService) DiscoverystatusGetExecute(r DiscoveryStatusAPIDiscoverystatusGetRequest) (*ListDiscoveryStatusResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *ListDiscoveryStatusResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "DiscoveryStatusAPIService.DiscoverystatusGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/discovery:status"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.maxResults != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_max_results", r.maxResults, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	if r.paging != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_paging", r.paging, "form", "")
	}
	if r.pageId != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_page_id", r.pageId, "form", "")
	}
	if r.filters != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "filters", r.filters, "form", "")
	}
	if r.extattrfilter != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "extattrfilter", r.extattrfilter, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type DiscoveryStatusAPIDiscoverystatusReferenceGetRequest struct {
	ctx            context.Context
	ApiService     DiscoveryStatusAPI
	reference      string
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Enter the field names followed by comma
func (r DiscoveryStatusAPIDiscoverystatusReferenceGetRequest) ReturnFields(returnFields string) DiscoveryStatusAPIDiscoverystatusReferenceGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r DiscoveryStatusAPIDiscoverystatusReferenceGetRequest) ReturnFields2(returnFields2 string) DiscoveryStatusAPIDiscoverystatusReferenceGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r DiscoveryStatusAPIDiscoverystatusReferenceGetRequest) ReturnAsObject(returnAsObject int32) DiscoveryStatusAPIDiscoverystatusReferenceGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r DiscoveryStatusAPIDiscoverystatusReferenceGetRequest) Execute() (*GetDiscoveryStatusResponse, *http.Response, error) {
	return r.ApiService.DiscoverystatusReferenceGetExecute(r)
}

/*
DiscoverystatusReferenceGet Get a specific discovery:status object

Returns a specific discovery:status object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the discovery:status object
	@return DiscoveryStatusAPIDiscoverystatusReferenceGetRequest
*/
func (a *DiscoveryStatusAPIService) DiscoverystatusReferenceGet(ctx context.Context, reference string) DiscoveryStatusAPIDiscoverystatusReferenceGetRequest {
	return DiscoveryStatusAPIDiscoverystatusReferenceGetRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return GetDiscoveryStatusResponse
func (a *DiscoveryStatusAPIService) DiscoverystatusReferenceGetExecute(r DiscoveryStatusAPIDiscoverystatusReferenceGetRequest) (*GetDiscoveryStatusResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *GetDiscoveryStatusResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "DiscoveryStatusAPIService.DiscoverystatusReferenceGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/discovery:status/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
