/*
Infoblox IPAM API

OpenAPI specification for Infoblox NIOS WAPI IPAM objects

API version: 2.13.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipam

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/Infoblox-CTO/infoblox-nios-go-client/internal"
)

type HostnamerewritepolicyAPI interface {
	/*
		Get Retrieve hostnamerewritepolicy objects

		Returns a list of hostnamerewritepolicy objects matching the search criteria

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return HostnamerewritepolicyAPIGetRequest
	*/
	Get(ctx context.Context) HostnamerewritepolicyAPIGetRequest

	// GetExecute executes the request
	//  @return ListHostnamerewritepolicyResponse
	GetExecute(r HostnamerewritepolicyAPIGetRequest) (*ListHostnamerewritepolicyResponse, *http.Response, error)
	/*
		ReferenceGet Get a specific hostnamerewritepolicy object

		Returns a specific hostnamerewritepolicy object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the hostnamerewritepolicy object
		@return HostnamerewritepolicyAPIReferenceGetRequest
	*/
	ReferenceGet(ctx context.Context, reference string) HostnamerewritepolicyAPIReferenceGetRequest

	// ReferenceGetExecute executes the request
	//  @return GetHostnamerewritepolicyResponse
	ReferenceGetExecute(r HostnamerewritepolicyAPIReferenceGetRequest) (*GetHostnamerewritepolicyResponse, *http.Response, error)
	/*
		ReferencePut Update a hostnamerewritepolicy object

		Updates a specific hostnamerewritepolicy object by reference

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param reference Reference of the hostnamerewritepolicy object
		@return HostnamerewritepolicyAPIReferencePutRequest
	*/
	ReferencePut(ctx context.Context, reference string) HostnamerewritepolicyAPIReferencePutRequest

	// ReferencePutExecute executes the request
	//  @return UpdateHostnamerewritepolicyResponse
	ReferencePutExecute(r HostnamerewritepolicyAPIReferencePutRequest) (*UpdateHostnamerewritepolicyResponse, *http.Response, error)
}

// HostnamerewritepolicyAPIService HostnamerewritepolicyAPI service
type HostnamerewritepolicyAPIService internal.Service

type HostnamerewritepolicyAPIGetRequest struct {
	ctx            context.Context
	ApiService     HostnamerewritepolicyAPI
	returnFields   *string
	returnFields2  *string
	maxResults     *int32
	returnAsObject *int32
	paging         *int32
	pageId         *string
	filters        *map[string]interface{}
	extattrfilter  *map[string]interface{}
}

// Enter the field names followed by comma
func (r HostnamerewritepolicyAPIGetRequest) ReturnFields(returnFields string) HostnamerewritepolicyAPIGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r HostnamerewritepolicyAPIGetRequest) ReturnFields2(returnFields2 string) HostnamerewritepolicyAPIGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Enter the number of results to be fetched
func (r HostnamerewritepolicyAPIGetRequest) MaxResults(maxResults int32) HostnamerewritepolicyAPIGetRequest {
	r.maxResults = &maxResults
	return r
}

// Select 1 if result is required as an object
func (r HostnamerewritepolicyAPIGetRequest) ReturnAsObject(returnAsObject int32) HostnamerewritepolicyAPIGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

// Control paging of results
func (r HostnamerewritepolicyAPIGetRequest) Paging(paging int32) HostnamerewritepolicyAPIGetRequest {
	r.paging = &paging
	return r
}

// Page id for retrieving next page of results
func (r HostnamerewritepolicyAPIGetRequest) PageId(pageId string) HostnamerewritepolicyAPIGetRequest {
	r.pageId = &pageId
	return r
}

func (r HostnamerewritepolicyAPIGetRequest) Filters(filters map[string]interface{}) HostnamerewritepolicyAPIGetRequest {
	r.filters = &filters
	return r
}

func (r HostnamerewritepolicyAPIGetRequest) Extattrfilter(extattrfilter map[string]interface{}) HostnamerewritepolicyAPIGetRequest {
	r.extattrfilter = &extattrfilter
	return r
}

func (r HostnamerewritepolicyAPIGetRequest) Execute() (*ListHostnamerewritepolicyResponse, *http.Response, error) {
	return r.ApiService.GetExecute(r)
}

/*
Get Retrieve hostnamerewritepolicy objects

Returns a list of hostnamerewritepolicy objects matching the search criteria

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return HostnamerewritepolicyAPIGetRequest
*/
func (a *HostnamerewritepolicyAPIService) Get(ctx context.Context) HostnamerewritepolicyAPIGetRequest {
	return HostnamerewritepolicyAPIGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return ListHostnamerewritepolicyResponse
func (a *HostnamerewritepolicyAPIService) GetExecute(r HostnamerewritepolicyAPIGetRequest) (*ListHostnamerewritepolicyResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *ListHostnamerewritepolicyResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "HostnamerewritepolicyAPIService.Get")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/hostnamerewritepolicy"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.maxResults != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_max_results", r.maxResults, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	if r.paging != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_paging", r.paging, "form", "")
	}
	if r.pageId != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_page_id", r.pageId, "form", "")
	}
	if r.filters != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "filters", r.filters, "form", "")
	}
	if r.extattrfilter != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "extattrfilter", r.extattrfilter, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type HostnamerewritepolicyAPIReferenceGetRequest struct {
	ctx            context.Context
	ApiService     HostnamerewritepolicyAPI
	reference      string
	returnFields   *string
	returnFields2  *string
	returnAsObject *int32
}

// Enter the field names followed by comma
func (r HostnamerewritepolicyAPIReferenceGetRequest) ReturnFields(returnFields string) HostnamerewritepolicyAPIReferenceGetRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r HostnamerewritepolicyAPIReferenceGetRequest) ReturnFields2(returnFields2 string) HostnamerewritepolicyAPIReferenceGetRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r HostnamerewritepolicyAPIReferenceGetRequest) ReturnAsObject(returnAsObject int32) HostnamerewritepolicyAPIReferenceGetRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r HostnamerewritepolicyAPIReferenceGetRequest) Execute() (*GetHostnamerewritepolicyResponse, *http.Response, error) {
	return r.ApiService.ReferenceGetExecute(r)
}

/*
ReferenceGet Get a specific hostnamerewritepolicy object

Returns a specific hostnamerewritepolicy object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the hostnamerewritepolicy object
	@return HostnamerewritepolicyAPIReferenceGetRequest
*/
func (a *HostnamerewritepolicyAPIService) ReferenceGet(ctx context.Context, reference string) HostnamerewritepolicyAPIReferenceGetRequest {
	return HostnamerewritepolicyAPIReferenceGetRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return GetHostnamerewritepolicyResponse
func (a *HostnamerewritepolicyAPIService) ReferenceGetExecute(r HostnamerewritepolicyAPIReferenceGetRequest) (*GetHostnamerewritepolicyResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *GetHostnamerewritepolicyResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "HostnamerewritepolicyAPIService.ReferenceGet")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/hostnamerewritepolicy/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}

type HostnamerewritepolicyAPIReferencePutRequest struct {
	ctx                   context.Context
	ApiService            HostnamerewritepolicyAPI
	reference             string
	hostnamerewritepolicy *Hostnamerewritepolicy
	returnFields          *string
	returnFields2         *string
	returnAsObject        *int32
}

// Object data to update
func (r HostnamerewritepolicyAPIReferencePutRequest) Hostnamerewritepolicy(hostnamerewritepolicy Hostnamerewritepolicy) HostnamerewritepolicyAPIReferencePutRequest {
	r.hostnamerewritepolicy = &hostnamerewritepolicy
	return r
}

// Enter the field names followed by comma
func (r HostnamerewritepolicyAPIReferencePutRequest) ReturnFields(returnFields string) HostnamerewritepolicyAPIReferencePutRequest {
	r.returnFields = &returnFields
	return r
}

// Enter the field names followed by comma, this returns the required fields along with the default fields
func (r HostnamerewritepolicyAPIReferencePutRequest) ReturnFields2(returnFields2 string) HostnamerewritepolicyAPIReferencePutRequest {
	r.returnFields2 = &returnFields2
	return r
}

// Select 1 if result is required as an object
func (r HostnamerewritepolicyAPIReferencePutRequest) ReturnAsObject(returnAsObject int32) HostnamerewritepolicyAPIReferencePutRequest {
	r.returnAsObject = &returnAsObject
	return r
}

func (r HostnamerewritepolicyAPIReferencePutRequest) Execute() (*UpdateHostnamerewritepolicyResponse, *http.Response, error) {
	return r.ApiService.ReferencePutExecute(r)
}

/*
ReferencePut Update a hostnamerewritepolicy object

Updates a specific hostnamerewritepolicy object by reference

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param reference Reference of the hostnamerewritepolicy object
	@return HostnamerewritepolicyAPIReferencePutRequest
*/
func (a *HostnamerewritepolicyAPIService) ReferencePut(ctx context.Context, reference string) HostnamerewritepolicyAPIReferencePutRequest {
	return HostnamerewritepolicyAPIReferencePutRequest{
		ApiService: a,
		ctx:        ctx,
		reference:  reference,
	}
}

// Execute executes the request
//
//	@return UpdateHostnamerewritepolicyResponse
func (a *HostnamerewritepolicyAPIService) ReferencePutExecute(r HostnamerewritepolicyAPIReferencePutRequest) (*UpdateHostnamerewritepolicyResponse, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []internal.FormFile
		localVarReturnValue *UpdateHostnamerewritepolicyResponse
	)

	localBasePath, err := a.Client.Cfg.ServerURLWithContext(r.ctx, "HostnamerewritepolicyAPIService.ReferencePut")
	if err != nil {
		return localVarReturnValue, nil, internal.NewGenericOpenAPIError(err.Error())
	}

	localVarPath := localBasePath + "/hostnamerewritepolicy/{reference}"
	localVarPath = strings.Replace(localVarPath, "{"+"reference"+"}", url.PathEscape(internal.ParameterValueToString(r.reference, "reference")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.hostnamerewritepolicy == nil {
		return localVarReturnValue, nil, internal.ReportError("hostnamerewritepolicy is required and must be specified")
	}

	if r.returnFields != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields", r.returnFields, "form", "")
	}
	if r.returnFields2 != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_fields+", r.returnFields2, "form", "")
	}
	if r.returnAsObject != nil {
		internal.ParameterAddToHeaderOrQuery(localVarQueryParams, "_return_as_object", r.returnAsObject, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := internal.SelectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := internal.SelectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.hostnamerewritepolicy
	req, err := a.Client.PrepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.Client.CallAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := internal.NewGenericOpenAPIErrorWithBody(localVarHTTPResponse.Status, localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.Client.Decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := internal.NewGenericOpenAPIErrorWithBody(err.Error(), localVarBody)
		return localVarReturnValue, localVarHTTPResponse, newErr
	}
	return localVarReturnValue, localVarHTTPResponse, nil
}
