/*
Infoblox DISCOVERY API

Testing DiscoverydiagnostictaskAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package discovery

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/Infoblox-CTO/infoblox-nios-go-client/discovery"
)

func TestDiscoverydiagnostictaskAPIService(t *testing.T) {

	apiClient := discovery.NewAPIClient()

	t.Run("Test DiscoverydiagnostictaskAPIService Get", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DiscoverydiagnostictaskAPI.Get(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DiscoverydiagnostictaskAPIService ReferenceGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var reference string

		resp, httpRes, err := apiClient.DiscoverydiagnostictaskAPI.ReferenceGet(context.Background(), reference).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DiscoverydiagnostictaskAPIService ReferencePut", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var reference string

		resp, httpRes, err := apiClient.DiscoverydiagnostictaskAPI.ReferencePut(context.Background(), reference).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
