/*
Infoblox GRID API

Testing GridX509certificateAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package grid

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/Infoblox-CTO/infoblox-nios-go-client/grid"
)

func TestGridX509certificateAPIService(t *testing.T) {

	apiClient := grid.NewAPIClient()

	t.Run("Test GridX509certificateAPIService Gridx509certificateGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.GridX509certificateAPI.Gridx509certificateGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GridX509certificateAPIService Gridx509certificateReferenceGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var reference string

		resp, httpRes, err := apiClient.GridX509certificateAPI.Gridx509certificateReferenceGet(context.Background(), reference).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
