/*
Infoblox GRID API

Testing GridServicerestartRequestAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package grid

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/Infoblox-CTO/infoblox-nios-go-client/grid"
)

func TestGridServicerestartRequestAPIService(t *testing.T) {

	apiClient := grid.NewAPIClient()

	t.Run("Test GridServicerestartRequestAPIService GridservicerestartrequestGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.GridServicerestartRequestAPI.GridservicerestartrequestGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GridServicerestartRequestAPIService GridservicerestartrequestReferenceGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var reference string

		resp, httpRes, err := apiClient.GridServicerestartRequestAPI.GridservicerestartrequestReferenceGet(context.Background(), reference).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
